@startuml
class dk.dtu.compute.se.pisd.roborally.controller.GameController {
+ AppController appController
+ Board board
- RESTController flicntr
+ void moveCurrentPlayerToSpace(Space)
+ void startProgrammingPhase()
- CommandCard generateRandomCommandCard()
+ void finishProgrammingPhase()
- void makeProgramFieldsVisible(int)
- void makeProgramFieldsInvisible()
+ void executePrograms()
+ void executeStep()
- void continuePrograms()
- void executeNextStep()
- void executeCommand(Player,Command)
+ void moveForward(Player)
+ void fastForward(Player)
+ void turnRight(Player)
+ void turnLeft(Player)
+ boolean moveCards(CommandCardField,CommandCardField)
+ void hitPlayer(Space,Heading)
+ void notImplemented()
+ void optionCard(Player)
+ void webPlayerSendProgram()
+ void webPlayerUpdateBoard()
}
@enduml