@startuml
class dk.dtu.compute.se.pisd.roborally.fileaccess.LoadBoard {
- {static} String BOARDSFOLDER
- {static} String DEFAULTBOARD
- {static} String JSON_EXT
+ {static} Board loadBoard(String)
+ {static} void insertInBoard(Board,String)
+ {static} void loadCardAndProg(Board,String,Player)
+ {static} void saveBoard(Board,String)
+ {static} String jsonFile()
+ {static} String jsonFileToSave()
}
@enduml