@startuml
class dk.dtu.compute.se.pisd.roborally.model.Board {
+ int width
+ int height
+ String boardName
- Integer gameId
- Space[][] spaces
- List<Player> players
- Player current
- Phase phase
- int step
- boolean stepMode
+ Integer getGameId()
+ void setGameId(int)
+ Space getSpace(int,int)
+ int getPlayersNumber()
+ void addPlayer(Player)
+ Player getPlayer(int)
+ Player getCurrentPlayer()
+ void setCurrentPlayer(Player)
+ Phase getPhase()
+ void setPhase(Phase)
+ int getStep()
+ void setStep(int)
+ boolean isStepMode()
+ void setStepMode(boolean)
+ int getPlayerNumber(Player)
+ Space getNeighbour(Space,Heading)
+ String getStatusMessage()
+ int getToken()
+ List<Player> getPlayers()
+ int getNrOfCurrentPlayer()
}


dk.dtu.compute.se.pisd.designpatterns.observer.Subject <|-- dk.dtu.compute.se.pisd.roborally.model.Board
@enduml